version: '3.8'
services:
  docelegance:
    container_name: frontenddocelegance
    build:
      context: .
      target: runner
    ports:
      - 80:3000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/
  db:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docs
    volumes:
      - db-data:/data:/var/lib/mysql
volumes:
  db-data:
